# Generated by Django 4.2.5 on 2023-12-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='/profile_images/default.jpeg', null=True, upload_to='profile_images/'),
        ),
    ]
