# Generated by Django 4.2.5 on 2023-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
