# Generated by Django 4.2.5 on 2023-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
