# Generated by Django 4.2.5 on 2023-12-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='/profile_images/default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
